### ISSUE TITLE
Erro ao subir nest-api

### ISSUE THREAD

**Issue by danieuuul** [codeedu/imersao8#5]
[ServerKafka] ERROR [Connection] Connection error: Client network socket disconnected before secure TLS connection was established {"timestamp":"2022-06-23T16:52:04.146Z","logger":"kafkajs","broker":"host.docker.internal:9094","clientId":"code-delivery-server","stack":"Error: Client network socket disconnected before secure TLS connection was established\n    at connResetException (internal/errors.js:570:14)\n    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)\n    at Object.onceWrapper (events.js:299:28)\n    at TLSSocket.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1184:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"} +26ms

**Comment by tiago-buso** [comment]
To com mesmo erro também.

EDIT:

Estou reparando que toda hora no arquivo do hosts está sendo alterado... some a configuração:

127.0.0.1 host.docker.internal

Também estou reparando que o serviço do simulador não parece funcionar corretamente.... (eu acho, fica travado nesse Attaching to simulator e não aparece nenhum log nada...)

<img width="805" alt="image" src="https://user-images.githubusercontent.com/7013966/175366725-2a9afc1e-7392-4531-96f4-ad00d9937768.png">

Em todo caso, colocar o hosts não resolveu o problema

**Comment by m4t3us89** [comment]
@danieuuul 
Dê uma olhada nessa issue https://github.com/codeedu/imersao8/issues/3

**Comment by tiago-buso** [comment]
> @danieuuul Dê uma olhada nessa issue #3

Para mim funcionou tirar o ssl mesmo. Não adiantou só colocar as chaves em branco.


Obrigado
